// my-app/src/components/Upload.tsx
import { Input, Select, Table, Td, Textarea, Tr, FormControl, FormLabel, Grid, GridItem, Button, Flex } from "@chakra-ui/react";
import { kStringMaxLength } from "node:buffer";
import { stringify } from "node:querystring";
import React, { ChangeEvent, FormEvent } from "react";
import { meQuery } from "../fetchUtils";
import { Kurs, Student } from "../utils";
import "../upload.css"

interface Props {}
interface State {
    meData: {
        student: Student,
        kursString: string,
        password: string;
        passwordConfirm: string;
    }
    selectedFile: File | null,
}


class Upload extends React.Component<Props, State> {
    constructor(props: Props){
        super(props);

        this.state = {
            meData: {
                student: null,
                kursString: "",
                password: "",
                passwordConfirm: "",
            },
            selectedFile: null,
        }
    }

    componentDidMount = () => {
        meQuery().then(data => {
            if(data.error !== null){
                return;
            }
            this.setState({meData: {
                ...this.state.meData,
                student: data.data,
                kursString: Kurs[data.data.kurs]
            }});
        })
    }

    handleChange = (e: ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => {
        switch (e.target.name){
            case "name":
                this.setState({meData: {
                    ...this.state.meData,
                    student: {
                        ...this.state.meData.student,
                        name: e.target.value
                    } as Student
                } });
                break;
            case "description":
                this.setState({meData: {
                    ...this.state.meData,
                    student: {
                        ...this.state.meData.student,
                        description: e.target.value
                    } as Student
                } });
                break;
            case "kurs":
                this.setState({meData: {
                    ...this.state.meData,
                    kursString: e.target.value
                } });
                break;
            case "image":
                const imageTarget = e.target as HTMLInputElement;
                if(imageTarget.files === null){
                    return
                }
                this.setState({selectedFile: imageTarget.files[0]});
                break;
            case "password":

                this.setState({
                    meData: {
                        ...this.state.meData,
                        password: e.target.value
                    }
                });
                break;
            case "passwordConfirm":                
                this.setState({
                    meData: {
                        ...this.state.meData,
                        passwordConfirm: e.target.value
                    }
                });
                break;
        }
    }

    handleSubmit = async (e: FormEvent) => {
        e.preventDefault();
        const form = new FormData();
        if(this.state.meData.student === null){
            return;
        }
        if(this.state.selectedFile === null){
            return
        }
        if(this.state.meData.password !== this.state.meData.passwordConfirm){
            return
        }

        form.append("name", this.state.meData.student?.name);
        form.append("kurs", this.state.meData.kursString);
        form.append("desc", this.state.meData.student?.description);
        form.append("file", this.state.selectedFile);
        form.append("password", this.state.meData.password);

        const options = {
            method: 'POST',
            body: form,
            credentials: "include"
        }
        if(this.state.meData.student._id === undefined){
            console.log("upload")
            await fetch("/api/students/upload", options as RequestInit)

            window.location.href = "/"
            return
        }
        console.log("update")
        await fetch("/api/students/update", options as RequestInit)

        window.location.href = "/"
    }

    createOptions = () => {
        let kurse: any[] = [];

        for(let i = 0; i < 8; i++){
            kurse.push(Kurs[i])
        }
    

        return(
            kurse.map((item, i) => {
                return(
                    <option key={i}>{item}</option>
                )
            })
        )
    }

    render= () => {
        return(
            <Flex justifyContent="center">
                <form style={{color: "inherit", width: "45%"}} onSubmit={this.handleSubmit}>
                    <Grid templateRows="repeat(5, 1fr)" w="100%" variant="unstyled" marginTop="3em">
                            <GridItem margin="1em" rowSpan={1} colSpan={2}>
                                <FormControl>
                                    <FormLabel>Dein Name: </FormLabel>
                                <Input color="primary" onChange={this.handleChange} name="name" value={this.state.meData.student?.name}></Input>
                                </FormControl>
                            </GridItem>
                            <GridItem margin="1em" rowSpan={1}  colSpan={2}>
                                <FormControl>
                                <FormLabel>Dein Kurs: </FormLabel>
                                <Select onChange={this.handleChange} value={this.state.meData.kursString} name="kurs" color="gray" >
                                    {this.createOptions()}
                                </Select>
                                </FormControl>
                            </GridItem>
                            <GridItem  margin="1em" rowSpan={1}  colSpan={4}>
                                <FormControl>
                                    <FormLabel>
                                        Lade ein wunderschönes Bild von dir hoch:
                                    </FormLabel>
                                    <Input onChange={this.handleChange} name="image" type="file"></Input>
                                </FormControl>
                            </GridItem>

                            <GridItem margin="1em" rowSpan={2} colSpan={4}>
                                <FormControl>
                                    <FormLabel>
                                        Über dich:
                                    </FormLabel>
                                    <Textarea height="40" onChange={this.handleChange} name="description" value={this.state.meData.student?.description} ></Textarea>
                                </FormControl>
                            </GridItem>
                            <GridItem margin="1em" rowSpan={1} colSpan={2}>
                                <FormControl>
                                    <FormLabel>
                                        Dein Passwort: 
                                    </FormLabel>
                                    <Input type="password" onChange={this.handleChange} name="password" value={this.state.meData.password} ></Input>
                                </FormControl>
                            </GridItem>
                            <GridItem margin="1em" rowSpan={1} colSpan={2}> 
                                <FormControl>
                                    <FormLabel>
                                        Dein Passwort bestätigen: 
                                    </FormLabel>
                                    <Input type="password" onChange={this.handleChange} name="passwordConfirm" value={this.state.meData.passwordConfirm} ></Input>
                                </FormControl>
                            </GridItem>
                            <GridItem>
                                <Button color="black" type="submit" margin="1em">Submit</Button>
                            </GridItem>
                    </Grid>
                    
                    
                </form>
            </Flex>
        )
    }
}



export default Upload;

// svelte-typescript-app/src/Upload.svelte
<script lang="ts">
import { Kurs } from "./kurs";
import { getMe } from "./queries";

    let meId: number | undefined;
    let meData;
    let kurse = [];

    let name: string;
    let bild;
    let kurs;
    let desc: string;
    let files;
    let password: string;
    let passwordConfirm: string;
    let errorMessage: string;

    for(let i = 0; i < 8; i++){
        kurse.push(Kurs[i])
    }

    getMe().then(data => {
        if(data !== undefined){
            meId = data._id
            meData = data;
            name = data.name;
            desc = data.description;
            kurs = Kurs[data.kurs];
            console.log(meId)
            return
        }
        meId = undefined;
    })
    console.log(meId)
    function validateForm(update = false): string {
        if(!password){
            return "Du brauchst ein Passwort."
        }
        if(passwordConfirm !== password){
            return "Deine Passwörter stimmen nicht überein."
        }
        if (!name){
            return "Dein Name kann nicht leer sein."
        }
        if (!desc){
            return "Deine Beschreibung kann nicht leer sein."
        }
        if (desc.length > 1113){
            return "Deine Beschreibung ist zu lang."
        }
        if(!update){
            if(!files){
                return "Du musst ein Bild von dir hochladen."
            }
            if (files[0].size > 1048576){
                return "Deine Datei ist zu groß."
            }
        }

        return null;
    }

    async function handleSubmit(){
        const formData = new FormData()
        const isFormInValid = validateForm()
        if(isFormInValid !== null){
            errorMessage = isFormInValid;
            return;
        }

        formData.append("name", name);
        formData.append("kurs", kurs)
        formData.append("desc", desc)
        formData.append("password", password)
        formData.append("file", files[0]);

        console.log(formData.get("name"))
        console.log(formData.get("kurs"))
        const options = {
            method: 'POST',
            body: formData,
            credentials: "include"
        }

        await fetch("/api/upload", options)

        window.location.href = "/"
    }

    async function handleSubmitUpdate() {
        const formData = new FormData()
        const isFormInValid = validateForm(true);
        if(isFormInValid !== null){
            errorMessage = isFormInValid;
            return;
        }

        formData.append("name", name);
        formData.append("kurs", kurs)
        formData.append("desc", desc)
        formData.append("password", password)
        if(files){
            formData.append("file", files[0]);
        }

        console.log(formData.get("name"))
        console.log(formData.get("kurs"))
        const options = {
            method: 'POST',
            body: formData,
            credentials: "include"
        }

        await fetch("/api/updateStudent", options)

        window.location.href = "/"        
    }
    //method="POST" action="http://localhost:3232/upload" 
</script>
<div class="container">
{#if meId === undefined}
<h2>Registrierung</h2>

<form on:submit|preventDefault={handleSubmit} enctype="multipart/form-data">

    <div class="row">
        <div class="six columns">
        <label for="name">Was ist dein Name?</label>
        <input class="u-full-width" type="text" name="name" id="name" bind:value={name}>
        </div>
        <div class="six columns">
            <label for="kurs">Dein Tutorenkurs:</label>
            <select class="u-full-width" id="kurs" name="kurs" bind:value={kurs}>
            {#each kurse as kurs}
                <option>{kurs}</option>
            {/each}
            </select>
        </div>
    </div>
    <div class="row">
        <label for="bild">Ein Bild von dir:</label>
        <!-- <FileUpload></FileUpload> -->
        <input type="file" accept=".png,.jpg,.jpeg" name="bild" id="bild" bind:files class="u-full-width">

    </div>
    <div class="row">
        <label for="desc">Erzähl was über dich:</label>
        <textarea class="u-full-width" name="desc" id="desc" bind:value={desc} />
    </div>
    <div class="row">
        <div class="six columns">
            <label for="password">Dein Passwort:</label>
            <input class="u-full-width" type="password" name="password" id="password" bind:value={password}>
        </div>
        <div class="six columns">
            <label for="passwordConfirm">Dein Passwort bestätigen:</label>
            <input class="u-full-width" type="password" name="passwordConfirm" id="passwordConfirm" bind:value={passwordConfirm}>
        </div>
            
    </div>        
    <input type="submit" value="Submit" class="button-primary">      

   

    
    <!-- <a onclick={handleSubmit} class="button">Submit</a> -->


</form>
{:else}
<h2>Update</h2>
<form on:submit|preventDefault={handleSubmitUpdate} enctype="multipart/form-data">
<div class="row">
    <div class="six columns">
    <label for="name">Was ist dein Name?</label>
    <input class="u-full-width" type="text" name="name" id="name" bind:value={name}>
    </div>
    <div class="six columns">
        <label for="kurs">Dein Tutorenkurs:</label>
        <select class="u-full-width" id="kurs" name="kurs" bind:value={kurs}>
        {#each kurse as kurs}
            <option>{kurs}</option>
        {/each}
        </select>
    </div>
</div>
<div class="row">
    <label for="bild">Ein Bild von dir:</label>
    <!-- <FileUpload></FileUpload> -->
    <input type="file" accept=".png,.jpg,.jpeg" name="bild" id="bild" bind:files class="u-full-width">

</div>
<div class="row">
    <label for="desc">Erzähl was über dich:</label>
    <textarea class="u-full-width" name="desc" id="desc" bind:value={desc} />
</div>
<div class="row">
    <div class="six columns">
        <label for="password">Dein Passwort:</label>
        <input class="u-full-width" type="password" name="password" id="password" bind:value={password}>
    </div>
    <div class="six columns">
        <label for="passwordConfirm">Dein Passwort bestätigen:</label>
        <input class="u-full-width" type="password" name="passwordConfirm" id="passwordConfirm" bind:value={passwordConfirm}>
    </div>
        
</div>        
<input type="submit" value="Submit" class="button-primary">
</form>
{/if}
{#if errorMessage}
    
<p class="error-message">! {errorMessage}</p>

{/if}
</div>

<style>
    h2{
        text-align: center;
		color: #ff3e00;
		text-transform: uppercase;
		font-weight: 50;
    }
    .container{
} 
    .error-message{
        color: red;
    }
</style>
