// svelte-typescript-app/src/HasVoted.svelte
<script lang="ts">
    import Chart, { ChartConfiguration } from "chart.js";
import { onMount } from "svelte";

    export let surveyData;
    export let survey;
    let hasBeenRendered = false;
    // console.log(survey.id)
    const makePieChartData = () => {
        const surveyId = survey.id;
        let data = {
            labels: [],
            datasets: [{
                backgroundColor: [          
                ],
                data: []
            }]
        }


        for(let i = 0; i < surveyData.optionen.length; i++){
            if(surveyData.optionen[i].umfrage === surveyId){
                data.labels.push(surveyData.optionen[i].title);
                data.datasets[0].backgroundColor.push(`rgb(${Math.round(Math.random()*255)},${Math.round(Math.random()*255)},${Math.round(Math.random()*255)})`)
                data.datasets[0].data.push(surveyData.optionen[i].numberOf);
            }
        }
        // console.log(surveyId)
        const thisChartCanvas = document.getElementById(survey.id) as HTMLCanvasElement;
        // console.log(thisChartCanvas)
        const ctx = thisChartCanvas.getContext("2d");
        const chart = new Chart(ctx, {type: "pie", data: data, options: {}});
        hasBeenRendered = true;
    }
    onMount(() => {
        makePieChartData();
    })
</script>

<div>
    <h3>{survey.title}</h3>
    <canvas id={survey.id}></canvas>
    <!-- <button class="button" on:click={makePieChartData}>Show Results</button> -->
</div>

// my-app/src/components/HasVoted.tsx
import React from "react";
import PieChart from "./PieChart";

interface Props{
    surveyData: any
    thisSurvey: any
}
interface State{}

class HasVoted extends React.Component<Props, State> {
    constructor(props: Props){
        super(props)
    }


    makeRandomColor = () => {
        return `rgb(${Math.round(Math.random()*255)},${Math.round(Math.random()*255)},${Math.round(Math.random()*255)})`;
    }


    getSurveyById = (id: number): string => {
        if(this.props.surveyData.umfragen === null){
            return "something went wrong :("
        }
        for(let i = 0; i < this.props.surveyData.umfragen.length; i++){
            
            if(this.props.surveyData.umfragen[i] !== null){
                if(this.props.surveyData.umfragen[i].id === id){
                    return this.props.surveyData.umfragen[i].title
                }
            }
        }
        return "something went wrong :("
    }

    getOptions = () => {
        let options = Array<any>();

        for(let i = 0; i < this.props.surveyData.optionen.length; i++){
            
            if(this.props.surveyData.optionen[i] !== null){
                if(this.props.surveyData.optionen[i].umfrage === this.props.thisSurvey.id){
                    options.push(this.props.surveyData.optionen[i]); 
                }
            }
        }    
        return options;    
    }

    render(){
        return(
            <div>
                <PieChart 
                    labels={this.getOptions().map((yep) => yep.title)}  
                        data={this.getOptions().map((yep) => yep.numberOf)}
                        backgroundColor={this.getOptions().map((yep) => this.makeRandomColor())}

                    />
            </div>
        )
    }
}

export default HasVoted;
