// svelte-typescript-app/src/Login.svelte
<script lang="ts">
    let name;
    let password;

    async function handleSubmit(){
        const formData = new FormData()
        formData.append("name", name);
        formData.append("password", password);

        const options = {
            method: 'POST',
            body: formData,
            credentials: "include"
        }
        await fetch("/api/login", options)
        window.location.href = "/"
    }
</script>
<div class="container">
    <h2>Login</h2>
<form on:submit|preventDefault={handleSubmit} enctype="multipart/form-data">
    <div class="row">
        <div class="six columns">
        <label for="name">Dein Name:</label>
        <input class="u-full-width" type="text" name="name" id="name" bind:value={name}>
    </div>
    <div class="six columns">
        <label for="password">Dein Passwort:</label>
        <input class="u-full-width" type="password" name="password" id="password" bind:value={password}>
        
    </div>
    <input type="submit" value="Submit" class="button-primary">
    </div>
</form>
</div>
<style>
    h2{
        text-align: center;
		color: #ff3e00;
		text-transform: uppercase;
		font-weight: 50;
    }
    .container{
}
</style>

// my-app/src/components/Login.tsx
import { Grid, GridItem } from "@chakra-ui/layout";
import { Button, Flex, FormControl, FormLabel, Input } from "@chakra-ui/react";
import React, { ChangeEvent, FormEvent } from "react";

interface Props {}
interface State {
    username: string;
    password: string;
}

class Login extends React.Component<Props, State> {
    constructor(props: Props){
        super(props)

        this.state = {
            username: "",
            password: ""
        }
    }

    handleChange = (e: ChangeEvent<HTMLInputElement>) => {
        switch (e.target.name){
            case "name":
                this.setState({
                    username: e.target.value
                })
                break;
            case "password":
                this.setState({
                    password: e.target.value
                })
                break;
        }
    }

    handleSubmit = async (e: FormEvent) => {
        e.preventDefault();
        const form = new FormData();
        form.append("name", this.state.username);
        form.append("password", this.state.password);

        console.log("my bick dig", this.state.password, this.state.username)
        const options = {
            method: 'POST',
            body: form,
            credentials: "include"
        }
        await fetch("/api/students/login", options as RequestInit)
        window.location.href = "/"
    }

    render(){
        return(
            <Flex  justifyContent="center">
                
                <form style={{width: "45%"}} onSubmit={this.handleSubmit}>
                    <Grid w="100%" marginTop="3em">
                        <GridItem margin="1em" colSpan={2}>
                            <FormControl>
                                <FormLabel>Dein Name: </FormLabel>
                                <Input color="primary" onChange={this.handleChange} name="name" value={this.state.username}></Input>
                            </FormControl>
                        </GridItem>
                        <GridItem margin="1em" colSpan={2}>
                            <FormControl>
                                <FormLabel>Dein Passwort: </FormLabel>
                                <Input color="primary" type="password" onChange={this.handleChange} name="password" value={this.state.password}></Input>
                            </FormControl>
                        </GridItem>
                        <GridItem margin="1em">
                            <Button color="black" type="submit">Submit</Button>
                        </GridItem>
                    </Grid>
                </form>
            </Flex>
        )
    }
}

export default Login;
